/*
 * Copyright (C) 1994-2019 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * PBS Pro is free software. You can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * PBS Pro is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * For a copy of the commercial license terms and conditions,
 * go to: (http://www.pbspro.com/UserArea/agreement.html)
 * or contact the Altair Legal Department.
 *
 * Altair’s dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of PBS Pro and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair’s trademarks, including but not limited to "PBS™",
 * "PBS Professional®", and "PBS Pro™" and Altair’s logos is subject to Altair's
 * trademark licensing policies.
 *
 */
/**
 * @file    req_qviewinfo.c
 *
 * @brief
 * 		req_qviewinfo.c - functions dealing with getting the job informationin  a running job.
 *
 * Functions included are:
 * 	req_reqinfo()
 * 	post_reqinfo_req()
 *
 *
 */

#include <pbs_config.h>   /* the master config generated by configure */

#include <stdio.h>
#include <sys/types.h>
#include "libpbs.h"
#include <signal.h>
#include "server_limits.h"
#include "list_link.h"
#include "attribute.h"
#include "server.h"
#include "credential.h"
#include "batch_request.h"
#include "job.h"
#include "work_task.h"
#include "pbs_error.h"
#include "log.h"
#include "pbs_nodes.h"
#include "svrfunc.h"
#include "acct.h"
#include <netdb.h> 

#include <stdlib.h> 
#include <string.h> 
#include <sys/socket.h> 


#define SA struct sockaddr 

/* Private Function local to this file */

static void post_reqinfo_req(struct work_task *);

/* Global Data Items: */

extern char *msg_reqinfo;


extern job  *chk_job_request(char *, struct batch_request *, int *,int *);

/**
 * @brief
 * 		req_reqinfo - service the reqinfo Job Request
 *
 *		This request sends (via MOM) a reqinfo to a running job.
 *
 * @param[in]	preq	- Pointer to batch request
 */



// Function designed for chat between client and server. 



void
req_reqinfo(struct batch_request *preq)
{
	int               jt;            /* job type */
	job		 *pjob;
	int		  rc;
(void)sprintf(log_buffer, msg_reqinfo, preq->rq_ind.rq_reqinfo.rq_jid);
	log_event(PBSEVENT_JOB, PBS_EVENTCLASS_JOB, LOG_INFO,
		preq->rq_ind.rq_reqinfo.rq_jid, log_buffer);
	if ((pjob = chk_job_request(preq->rq_ind.rq_reqinfo.rq_jid, preq, &jt,NULL)) == 0)
		return;

	/* the job must be running */

	if (pjob->ji_qs.ji_state != JOB_STATE_RUNNING) {
		req_reject(PBSE_BADSTATE, 0, preq);
		return;
	}

	/* pass the request on to MOM */

	rc = relay_to_mom(pjob, preq, post_reqinfo_req);
	if (rc)
		req_reject(rc, 0, preq);	/* unable to get to MOM */

	/* After MOM acts and replies to us, we pick up in post_message_req() */
}



/**
 * @brief
 * 		post_reqinfo_req - complete a reqinfo Job Request
 *
 * @param[in]	pwt	-	work task structure
 */

static void
post_reqinfo_req(struct work_task *pwt)
{
	struct batch_request *preq;

	if (pwt->wt_aux2 != 1) /* not rpp */
		svr_disconnect(pwt->wt_event);	/* close connection to MOM */
	preq = pwt->wt_parm1;
	preq->rq_conn = preq->rq_orgconn;  /* restore socket to client */


	if (preq->rq_reply.brp_code)
		req_reject(preq->rq_reply.brp_code, 0, preq);
	else
		reply_ack(preq);
}

